<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="chenjuan" ignored="0" name="Test" tests="61" failures="61" timestamp="25 六月 2019 00:31:16 GMT" time="0.904" errors="0">
  <testcase name="assertResults" time="0.187" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- assertResults -->
  <testcase name="f" time="0.01" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.0" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.0" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.0" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.01" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.0" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.01" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.0" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.0" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.0" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.0" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.01" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.0" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.0" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.01" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.0" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.01" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.0" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.0" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.0" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.0" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.0" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.0" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.01" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.0" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.09" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.0" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.0" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.0" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.01" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.0" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.0" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.0" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.01" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.0" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.01" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.0" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.01" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.0" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.0" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.01" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.0" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.0" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.0" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.0" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.0" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.0" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.01" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.0" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.01" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.01" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.0" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.01" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.0" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.01" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.0" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.0" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.01" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.0" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.0" classname="com.music.allureTest.DataDrivenInvoke">
    <failure type="java.lang.AssertionError" message="expected [PASS] but found [读取到的数据]">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [读取到的数据]
at com.music.allureTest.DataDrivenInvoke.assertResults(DataDrivenInvoke.java:43)
at com.music.allureTest.DataDrivenInvoke.f(DataDrivenInvoke.java:36)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- f -->
</testsuite> <!-- Test -->
